### ISSUE TITLE
Support for default methods

### ISSUE THREAD

**Issue by vorner** [dtolnay/inherent#1]
Hello

Let's say I have this:

```rust
trait Answer {
  fn print_answer(&self, a: usize);
  fn print_default_answer(&self) {
    self.print_answer(42);
  }
}

struct Sage;

#[inherent]
impl Answer for Sage {
  fn print_answer(&self, a: usize) {
    println!("{}", a);
  }
}
```

This gives only the `print_answer` as an inherent method of `Sage`. So I'd like to ask, is there anything that can be done about it?

I see two difficulties:
* The proc-macro doesn't know about the default methods. For this I think it would be OK to require them to be somehow listed explicitly, eg as headers without bodies.
* The other one is, what code to actually emit. If I'm not mistaken, the proc-macro emits both the trait impl and the ordinary (inherent) impl block ‒ so, would it work to not emit this method inside the trait impl and emit something like this inside the inherent one?

```rust
fn print_default_answer(&self) {
    <Self as Sage>::print_default_answer(self);
}
```

Do you see any roadblocks in this direction? Should I try implementing it and submitting a PR?

**Comment by dtolnay** [comment]
I would accept a PR to fix this. You're right that we need the signature to be provided. Something like this would work:

```rust
#[inherent]
impl Answer for Sage {
    fn print_answer(&self, a: usize) {
        println!("{}", a);
    }
    default! {
        fn print_default_answer(&self);
    }
}
```

where the methods with no body are omitted from the trait impl block but included in the inherent impl block.

**Comment by vorner** [comment]
I'll probably attempt writing it, but not right now, it'll take some time before I get around to it.

My original idea was not to use the `default!`, but just list them without bodies, eg:

```rust
#[inherent]
impl Answer for Sage {
    fn print_answer(&self, a: usize) {
        println!("{}", a);
    }
    fn print_default_answer(&self);
}
```

**Comment by vorner** [comment]
Hmm. I've discovered the compiler first parses the whole impl block, insisting it's valid before passing it on to the proc-macro-attribute. That means it refuses the body-less method signature without even calling it :-(.

So I'll proceed with the `default!` suggestion, as that one should work, even though I consider it less convenient.
