### ISSUE TITLE
Why upgrading to a major version of `syn` when releasing a patch version of `inherent`?

### ISSUE THREAD

**Issue by billy1624** [dtolnay/inherent#18]
As title. I guess `syn v2` split more types into feature guarded module compared with `syn v1`?

The affected CI: https://github.com/SeaQL/sea-query/actions/runs/4462345887/jobs/7836825695

**Comment by billy1624** [comment]
Interesting. Seems `thiserror` also upgraded to `syn v2` in recent patch release.

**Comment by billy1624** [comment]
Hey @dtolnay, I'm writing to inform and see if it's intentional or not. Appreciated to what you did for the Rust community. Cheers!! :)

**Comment by billy1624** [comment]
UPDATE: the root cause of the failing CI is documented here https://github.com/SeaQL/sea-query/pull/624

**Comment by dtolnay** [comment]
Seems like this was a bug in sea-query.
