### ISSUE TITLE
Ability to inherit documentation from the trait?

### ISSUE THREAD

**Issue by vorner** [dtolnay/inherent#3]
Hello

I don't think there's an obvious solution to this one, but I want to ask anyway in case I'm overlooking something. Is it possible to somehow inherit the documentation from the trait?

What I mean, if I have this code:

```rust
trait T {
  /// Do something really useful.
  fn foo(&self);
}

struct X;

#[inherent]
impl T for X {
    fn foo(&self) {
      println!("foo!");
    }
}
```

I can now call `X.foo()`. But the documentation for `X` will list `foo()` without the documentation. It would be great when if none is provided inside the impl, the one from `T::foo` would be used as a fallback. But I don't see how ‒ the proc macro clearly doesn't have access to the trait itself :-(.

**Comment by dtolnay** [comment]
I don't know of any way to make this work, unfortunately. Maybe by building #\[inherent\] into rustc.

**Comment by vorner** [comment]
Putting the whole `#[inherent]` in there seems a bit of an overkill :-(.

I'm wondering about two possible extensions, but I'm unsure about either being worth it.

* Some kind of `#[doc(copy_from = T::foo)]` attribute so rustdoc could copy the documentation from there.
* Ability of proc-macros to request further information from rustc (eg. looking up the trait by the ident and getting an additional read-only token stream). I guess this could be useful to other proc macros too, but I suspect this being problematic due to ordering of macro/proc-macro expansion.

So I'm torn about trying to pursue one of the above on internals.rust-lang.org and just closing this one.

**Comment by vorner** [comment]
One idea for a half-way solution. With adding some attribute on the field or the whole impl block, the macro could generate at least the `See $Trait::$method` documentation links. Should I try if this works?

**Comment by dtolnay** [comment]
I would accept a PR to add a doc comment with a link to the trait method on any function that doesn't already have any doc comment.

```rust
/// See [`$Trait::$method`].
```
